
spring:
  application:
    name: demo
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.194.114:9092   #Kafka的消息中间件服务器
          zk-nodes: 192.168.194.114:2181  #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true  #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          required-acks: -1

      bindings:
        ## 新版本固定格式  channel名字-{out/in}-{index}
        demoChannel-out-0:
          destination: demoExchange
          contentType: application/json
        demoChannel-in-0:
          destination: demoExchange
          contentType: application/json
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"